name: Integração Contínua

on: [pull_request]

jobs:
  build:
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Rodar Testes Automáticos
      env:
       SECRET_KEY: 'django-insecure-lmfi&a*z%=30yf8r&mkr$s=(o+4su_m(y#dlguzyuj2a4uf2lt'
      run: |
          pytest
